services:
  volunteer-manager:
    image: aimlp.azurecr.io/volunteer-manager:latest
    container_name: volunteer-manager
    command: bash -c ./entrypoint.sh
    ports:
      - 2137:2137
    environment:
      - APP_NAME=VOLUNTEER-MANAGER
      - LOGGING_LEVEL=DEBUG
      - COLORED_LOGGING=True
      - DATABASE_URL=postgresql://user:password@db:5432/db
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14.5-alpine3.16
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db