services:
  volunteer-manager:
    image: aimlp.azurecr.io/volunteer-manager:latest
    container_name: volunteer-manager
    command: bash -c ./entrypoint.sh
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_ENV=DOCKER
    depends_on:
      - db

  db:
    image: docker.io/library/mysql:5.7
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: azure_file
    driver_opts:
      share_name: ${FILE_SHARE_NAME}
      storage_account_name: ${STORAGE_ACCOUNT_NAME}
      storageaccountkey: ${STORAGE_ACCOUNT_KEY}