services:
  volunteer-manager:
    image: volunteer-manager
    container_name: volunteer-manager
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.server:app --host 0.0.0.0 --port 2137'
    ports:
      - 2137:2137
    environment:
      - APP_NAME=VOLUNTEER-MANAGER
      - LOGGING_LEVEL=DEBUG
      - COLORED_LOGGING=True
      - DATABASE_URL=postgresql://user:password@db:5432/project_db
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db

volumes:
  postgres_data: