services:
  volunteer-manager:
    image: volunteer-manager
    container_name: volunteer-manager
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/${DB_PORT}; do sleep 1; done; uvicorn app.server:app --host 0.0.0.0 --port ${APP_PORT}'
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_NAME=VOLUNTEER-MANAGER
      - LOGGING_LEVEL=DEBUG
      - COLORED_LOGGING=True
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/project_db
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14.5-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=project_db

volumes:
  postgres_data: