services:
  volunteer-manager:
    image: volunteer-manager
    container_name: volunteer-manager
    build:
      context: .
    command: bash -c ./entrypoint.sh
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_ENV=DOCKER
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14.5-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=project_db

volumes:
  postgres_data: