services:
  volunteer-manager:
    image: volunteer-manager
    container_name: volunteer-manager
    build:
      context: .
    command: bash -c ./entrypoint.sh
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - APP_ENV=DOCKER
    depends_on:
      - db

  db:
    image: docker.io/library/mariadb:10.9.3
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mariadb_data: